# Generated by Django 4.2.11 on 2026-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=1)),
                ('provider_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('provider_id', models.IntegerField()),
            ],
            options={
                'db_table': '"service-requests"',
            },
        ),
    ]
