# Generated by Django 6.0.3 on 2026-04-03 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_core.provider'),
            preserve_default=False,
        ),
    ]
