# Generated by Django 6.0.3 on 2026-03-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_service_provider'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='provider',
            table='provider',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
