# Generated by Django 6.0.3 on 2026-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_provider_alter_servicerequest_provider_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='provider',
        ),
        migrations.AddField(
            model_name='provider',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='provider_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='provider',
            table='api_core_provider',
        ),
        migrations.AlterModelTable(
            name='servicerequest',
            table='service-requests',
        ),
    ]
