# Generated by Django 6.0.3 on 2026-03-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_provider_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/'),
        ),
        migrations.AlterModelTable(
            name='provider',
            table='service_providers',
        ),
        migrations.AlterModelTable(
            name='service',
            table='admin_services',
        ),
        migrations.AlterModelTable(
            name='user',
            table='app_users',
        ),
    ]
