# Generated by Django 6.0.3 on 2026-03-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0003_alter_provider_aadhaar_image_alter_provider_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
