# Generated by Django 6.0.3 on 2026-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0003_remove_servicerequest_provider_provider_is_available_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='provider_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.CharField(max_length=200),
        ),
    ]
