# Generated by Django 6.0.3 on 2026-03-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='provider',
            table='admin_service_providers',
        ),
    ]
