# Generated by Django 5.2.12 on 2026-03-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='aadhaar_image',
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='provider',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='provider',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='provider',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
