# Generated by Django 6.0.3 on 2026-04-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_service_address_provider'),
        ('api_core', '0005_alter_provider_table'),
    ]

    operations = [
    ]
