# Generated by Django 6.0.3 on 2026-04-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0006_merge_20260402_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar/'),
        ),
        migrations.AddField(
            model_name='provider',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='providers/'),
        ),
        migrations.AddField(
            model_name='provider',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provider',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='provider',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='api_core.service'),
        ),
    ]
